//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.15 at 01:41:48 PM CET 
//


package fuse.esb.examples.jmsderbyjta.model;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ContactInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="homeAddress" type="{}Address" minOccurs="0"/>
 *         &lt;element name="homePhone" type="{}Phone" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactInfo", propOrder = {
    "homeAddress",
    "homePhone"
})
@Entity(name = "ContactInfo")
@Table(name = "CONTACTINFO")
@Inheritance(strategy = InheritanceType.JOINED)
public class ContactInfo
    implements Equals, HashCode
{

    protected Address homeAddress;
    protected Phone homePhone;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the homeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    @ManyToOne(targetEntity = Address.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "HOMEADDRESS_CONTACTINFO_HJID")
    public Address getHomeAddress() {
        return homeAddress;
    }

    /**
     * Sets the value of the homeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setHomeAddress(Address value) {
        this.homeAddress = value;
    }

    /**
     * Gets the value of the homePhone property.
     * 
     * @return
     *     possible object is
     *     {@link Phone }
     *     
     */
    @ManyToOne(targetEntity = Phone.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "HOMEPHONE_CONTACTINFO_HJID")
    public Phone getHomePhone() {
        return homePhone;
    }

    /**
     * Sets the value of the homePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phone }
     *     
     */
    public void setHomePhone(Phone value) {
        this.homePhone = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ContactInfo)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ContactInfo that = ((ContactInfo) object);
        {
            Address lhsHomeAddress;
            lhsHomeAddress = this.getHomeAddress();
            Address rhsHomeAddress;
            rhsHomeAddress = that.getHomeAddress();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "homeAddress", lhsHomeAddress), LocatorUtils.property(thatLocator, "homeAddress", rhsHomeAddress), lhsHomeAddress, rhsHomeAddress)) {
                return false;
            }
        }
        {
            Phone lhsHomePhone;
            lhsHomePhone = this.getHomePhone();
            Phone rhsHomePhone;
            rhsHomePhone = that.getHomePhone();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "homePhone", lhsHomePhone), LocatorUtils.property(thatLocator, "homePhone", rhsHomePhone), lhsHomePhone, rhsHomePhone)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Address theHomeAddress;
            theHomeAddress = this.getHomeAddress();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "homeAddress", theHomeAddress), currentHashCode, theHomeAddress);
        }
        {
            Phone theHomePhone;
            theHomePhone = this.getHomePhone();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "homePhone", theHomePhone), currentHashCode, theHomePhone);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
