//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.15 at 01:41:48 PM CET 
//


package fuse.esb.examples.jmsderbyjta.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fuse.esb.examples.jmsderbyjta.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Phone_QNAME = new QName("", "Phone");
    private final static QName _Address_QNAME = new QName("", "Address");
    private final static QName _ContactInfo_QNAME = new QName("", "ContactInfo");
    private final static QName _User0_QNAME = new QName("", "User0");
    private final static QName _Coordinates_QNAME = new QName("", "Coordinates");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fuse.esb.examples.jmsderbyjta.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User0 }
     * 
     */
    public User0 createUser0() {
        return new User0();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link User0 .Adresses }
     * 
     */
    public User0 .Adresses createUser0Adresses() {
        return new User0 .Adresses();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Phone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Phone")
    public JAXBElement<Phone> createPhone(Phone value) {
        return new JAXBElement<Phone>(_Phone_QNAME, Phone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address")
    public JAXBElement<Address> createAddress(Address value) {
        return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ContactInfo")
    public JAXBElement<ContactInfo> createContactInfo(ContactInfo value) {
        return new JAXBElement<ContactInfo>(_ContactInfo_QNAME, ContactInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User0 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User0")
    public JAXBElement<User0> createUser0(User0 value) {
        return new JAXBElement<User0>(_User0_QNAME, User0 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Coordinates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Coordinates")
    public JAXBElement<Coordinates> createCoordinates(Coordinates value) {
        return new JAXBElement<Coordinates>(_Coordinates_QNAME, Coordinates.class, null, value);
    }

}
